# Generated by Django 4.2.7 on 2023-11-02 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('sunlight', models.CharField(choices=[('LIGHT_EXPOSURE', 'Light Exposure'), ('PARTIAL_SHADE', 'Partial Shade'), ('SHADE', 'Shade')], default='LIGHT_EXPOSURE', max_length=20)),
                ('sun_exposure', models.CharField(choices=[('DIRECT_SUN', 'Direct Sun'), ('NO_DIRECT_SUN', 'No Direct Sun')], default='DIRECT_SUN', max_length=20)),
                ('water_frequency_summer', models.IntegerField()),
                ('water_frequency_winter', models.IntegerField()),
                ('last_watered', models.DateTimeField(blank=True, null=True)),
                ('leaf_mist', models.BooleanField(default=False)),
                ('fertilizer', models.BooleanField(default=False)),
                ('fertilizer_season', models.CharField(blank=True, choices=[('AUTUMN', 'Autumn'), ('SPRING', 'Spring')], max_length=20, null=True)),
                ('last_fertilized', models.DateTimeField(blank=True, null=True)),
                ('repotting', models.BooleanField(default=False)),
                ('repotting_season', models.CharField(blank=True, choices=[('AUTUMN', 'Autumn'), ('SPRING', 'Spring')], max_length=20, null=True)),
                ('last_repotted', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email_notifications', models.BooleanField(default=False)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('preferred_notification_hour', models.IntegerField(default=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
