# Generated by Django 4.2.7 on 2023-11-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyPlants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='fertilizer_season',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='repotting_season',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=20, null=True),
        ),
    ]
