# Generated by Django 4.2.7 on 2023-11-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyPlants', '0002_alter_plant_fertilizer_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationcenter',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
