# Generated by Django 4.2.7 on 2023-11-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyPlants', '0004_notificationcenter_enable_in_app_notifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='notificationcenter',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='notificationcenter',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='plantuser',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='plantuser',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
