# Generated by Django 4.2.7 on 2023-11-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyPlants', '0004_alter_notificationcenter_last_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='extra_tips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
