# Generated by Django 4.2.7 on 2023-11-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyPlants', '0005_rename_created_at_notification_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='next_fertilize_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='next_repotting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='next_water_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='should_fertilize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='should_repot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='should_water',
            field=models.BooleanField(default=False),
        ),
    ]
