# Generated by Django 4.2.7 on 2023-11-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyPlants', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
