# Generated by Django 4.2.7 on 2023-11-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyPlants', '0008_alter_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantuser',
            name='has_ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
