# Generated by Django 4.2.7 on 2023-11-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyPlants', '0010_alter_plant_sun_exposure_alter_plant_sunlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sun_exposure',
            field=models.CharField(blank=True, choices=[('DIRECT_SUN', 'Direct Sun'), ('NO_DIRECT_SUN', 'No Direct Sun')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(blank=True, choices=[('LIGHT_EXPOSURE', 'Light Exposure'), ('PARTIAL_SHADE', 'Partial Shade'), ('SHADE', 'Shade')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_frequency_summer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_frequency_winter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
