# Generated by Django 4.2.7 on 2023-11-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyPlants', '0011_alter_plant_sun_exposure_alter_plant_sunlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
