# Generated by Django 5.0 on 2023-12-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyPlants', '0012_plant_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='needs_care',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(should_water=True, then=models.Value(True)), models.When(should_repot=True, then=models.Value(True)), models.When(should_fertilize=True, then=models.Value(True)), default=models.Value(False)), output_field=models.BooleanField()),
        ),
    ]
