# Generated by Django 5.0 on 2024-01-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyPlants', '0014_alter_plant_name_alter_plantuser_has_ai_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='plantuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
