# Generated by Django 4.2.7 on 2023-11-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyPlants', '0008_alter_plant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPlantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('in_progress', 'In Progress'), ('not_started', 'Not Started')], default='not_started', max_length=20)),
                ('json_answer', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plant_answers', to='pyPlants.plant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
