# Generated by Django 4.2.7 on 2023-11-28 14:19

from django.db import migrations, models
import pyPlants.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiplantanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pyPlants.utils.plant_logos_directory_path),
        ),
    ]
