# Generated by Django 4.2.7 on 2023-11-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiplantanswer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiplantanswer',
            name='is_checking_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiplantanswer',
            name='is_generating_image',
            field=models.BooleanField(default=False),
        ),
    ]
